# Generated by Django 2.2.6 on 2019-11-22 21:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion_usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_servicio', models.CharField(max_length=80)),
                ('valor_servicio', models.IntegerField()),
                ('descripcion_servicio', models.CharField(max_length=200)),
                ('fecha_servicio', models.DateTimeField()),
                ('cliente', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
